<?php

namespace Plugin\SampleRssFeed\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\SampleRssFeed\Entity\Config;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Config::class);
    }

    /**
     * @param int $id
     *
     * @return null|Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * @param int $id
     *
     * @return int
     */
    public function getFeedLength($id = 1)
    {
        $config = $this->get($id);

        return $config ? $config->getFeedLength() : 10;
    }
}
